# Generated by Django 2.0.7 on 2018-07-23 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_field_fix_and_editable'),
        ('telegramtoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtoken',
            name='administrator',
            field=models.ForeignKey(default=1, help_text='Wallet-ID of licensor. By default the stream publisher Wallet-ID is assumed to be the licensor. This assumption can be overridden by providing an explicit list of one or more Wallet-IDs. Future extensibility: licensor_identifier_type.', on_delete=django.db.models.deletion.CASCADE, to='organizations.OrganizationUser', verbose_name='Telegram Administrator'),
            preserve_default=False,
        ),
    ]
